# -*- coding: utf-8 -*-
"""Solar deploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NipoW9ZvWwxIxfux-RXlNg_RutCGnmcw
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt

st.set_page_config(page_title="Solar Flare Forecast", layout="wide")

st.title("🌞 Solar Flare Early Warning Dashboard")

# Sidebar
st.sidebar.header("Controls")

uploaded = st.sidebar.file_uploader("Upload dataset CSV")

threshold = st.sidebar.slider("Risk threshold", 0.2, 0.8, 0.5, 0.01)

# Load artifacts
model = load_model("solar_flare_model.h5")
scaler = joblib.load("scaler.pkl")

window = 40

def create_sequences(X, window):
    Xs = []
    for i in range(len(X)-window):
        Xs.append(X[i:i+window])
    return np.array(Xs)

if uploaded:

    df = pd.read_csv(uploaded)

    st.subheader("Dataset preview")
    st.dataframe(df.head())

    # ===== FEATURES =====
    FEATURE_LIST = [
        # paste your exact features here
    ]

    X_scaled = scaler.transform(df[FEATURE_LIST])
    X_seq = create_sequences(X_scaled, window)

    pred_prob = model.predict(X_seq).flatten()
    pred_class = (pred_prob > threshold).astype(int)

    # ===== METRICS ROW =====
    col1, col2, col3 = st.columns(3)

    col1.metric("Mean risk", f"{pred_prob.mean():.3f}")
    col2.metric("Max risk", f"{pred_prob.max():.3f}")
    col3.metric("Alerts", int(pred_class.sum()))

    # ===== RISK TIMELINE =====
    st.subheader("Risk timeline")

    fig, ax = plt.subplots(figsize=(12,4))
    ax.plot(pred_prob, label="Risk")
    ax.axhline(threshold, linestyle="--", label="Threshold")
    ax.legend()
    st.pyplot(fig)

    # ===== EVENT VIEW =====
    st.subheader("Predicted alerts")

    alert_idx = np.where(pred_class==1)[0]
    st.write(f"Detected {len(alert_idx)} high-risk windows")

    # ===== MODEL INFO =====
    with st.expander("Model details"):
        st.write("Attention LSTM with temporal + GOES features")
        st.write(f"Window size: {window}")
        st.write("Task: Early warning flare prediction")

else:
    st.info("Upload a dataset to start.")

